// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → navigation*
 */
export interface FooterDocumentDataNavigationItem {
  /**
   * link label field in *Footer → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * link field in *Footer → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * navigation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<FooterDocumentDataNavigationItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | SidePanelSlice
  | BlowUpSlice
  | SideCardsSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Browser Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.browser_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  browser_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Display field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.display
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  display: prismic.KeyTextField;

  /**
   * logo symbol field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_symbol
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_symbol: prismic.ImageField<never>;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo: prismic.KeyTextField;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Beta Access field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.beta_access
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  beta_access: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Header Button Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_button_text: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomepageDocument
  | SettingsDocument;

/**
 * Primary content in *BlowUp → Default → Primary*
 */
export interface BlowUpSliceDefaultPrimary {
  /**
   * Main_label field in *BlowUp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blow_up.default.primary.main_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_label: prismic.KeyTextField;

  /**
   * Sub label field in *BlowUp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blow_up.default.primary.sub_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_label: prismic.KeyTextField;

  /**
   * BlowUp Ui field in *BlowUp → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blow_up.default.primary.blowup_ui
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blowup_ui: prismic.ImageField<never>;

  /**
   * Back Glow field in *BlowUp → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blow_up.default.primary.back_glow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  back_glow: prismic.ImageField<never>;

  /**
   * Swoosh field in *BlowUp → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blow_up.default.primary.swoosh
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  swoosh: prismic.ImageField<never>;
}

/**
 * Default variation for BlowUp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlowUpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlowUpSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlowUp*
 */
type BlowUpSliceVariation = BlowUpSliceDefault;

/**
 * BlowUp Shared Slice
 *
 * - **API ID**: `blow_up`
 * - **Description**: BlowUp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlowUpSlice = prismic.SharedSlice<"blow_up", BlowUpSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Intro Quote field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.intro_quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_quote: prismic.RichTextField;

  /**
   * subquote field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subquote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subquote: prismic.KeyTextField;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Intro Subquote field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.intro_subquote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_subquote: prismic.RichTextField;

  /**
   * Email Field field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.email_field
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  email_field: prismic.ImageField<never>;

  /**
   * email input field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.email_input
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email_input: prismic.RichTextField;

  /**
   * UI Mock field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ui_mock
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ui_mock: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *SideCards → Default → Primary → Cards*
 */
export interface SideCardsSliceDefaultPrimaryCardsItem {
  /**
   * Top field in *SideCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.cards[].top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top: prismic.KeyTextField;

  /**
   * Bottom field in *SideCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.cards[].bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bottom: prismic.KeyTextField;

  /**
   * Symbol field in *SideCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.cards[].symbol
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  symbol: prismic.ImageField<never>;
}

/**
 * Primary content in *SideCards → Default → Primary*
 */
export interface SideCardsSliceDefaultPrimary {
  /**
   * Label field in *SideCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Sublabel field in *SideCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.sublabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sublabel: prismic.KeyTextField;

  /**
   * Ui Cutout field in *SideCards → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.ui_cutout
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ui_cutout: prismic.ImageField<never>;

  /**
   * Cards field in *SideCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: side_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<SideCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for SideCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SideCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SideCards*
 */
type SideCardsSliceVariation = SideCardsSliceDefault;

/**
 * SideCards Shared Slice
 *
 * - **API ID**: `side_cards`
 * - **Description**: SideCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideCardsSlice = prismic.SharedSlice<
  "side_cards",
  SideCardsSliceVariation
>;

/**
 * Primary content in *SidePanel → Default → Primary*
 */
export interface SidePanelSliceDefaultPrimary {
  /**
   * Label field in *SidePanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Sublabel field in *SidePanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.default.primary.sublabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sublabel: prismic.KeyTextField;

  /**
   * UI cutout field in *SidePanel → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.default.primary.ui_cutout
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ui_cutout: prismic.ImageField<never>;

  /**
   * link field in *SidePanel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link text field in *SidePanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for SidePanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidePanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SidePanelSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SidePanel → Buttonless → Primary*
 */
export interface SidePanelSliceButtonlessPrimary {
  /**
   * Label field in *SidePanel → Buttonless → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.buttonless.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Sublabel field in *SidePanel → Buttonless → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.buttonless.primary.sublabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sublabel: prismic.KeyTextField;

  /**
   * UI cutout field in *SidePanel → Buttonless → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_panel.buttonless.primary.ui_cutout
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ui_cutout: prismic.ImageField<never>;
}

/**
 * Buttonless variation for SidePanel Slice
 *
 * - **API ID**: `buttonless`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidePanelSliceButtonless = prismic.SharedSliceVariation<
  "buttonless",
  Simplify<SidePanelSliceButtonlessPrimary>,
  never
>;

/**
 * Slice variation for *SidePanel*
 */
type SidePanelSliceVariation = SidePanelSliceDefault | SidePanelSliceButtonless;

/**
 * SidePanel Shared Slice
 *
 * - **API ID**: `side_panel`
 * - **Description**: SidePanel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidePanelSlice = prismic.SharedSlice<
  "side_panel",
  SidePanelSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      BlowUpSlice,
      BlowUpSliceDefaultPrimary,
      BlowUpSliceVariation,
      BlowUpSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SideCardsSlice,
      SideCardsSliceDefaultPrimaryCardsItem,
      SideCardsSliceDefaultPrimary,
      SideCardsSliceVariation,
      SideCardsSliceDefault,
      SidePanelSlice,
      SidePanelSliceDefaultPrimary,
      SidePanelSliceButtonlessPrimary,
      SidePanelSliceVariation,
      SidePanelSliceDefault,
      SidePanelSliceButtonless,
    };
  }
}
